name: Upload Artifacts to Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to upload assets to"
        required: true
        default: "v1.0.4"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-cli
          path: ./artifacts/linux
        continue-on-error: true

      - name: Download MacOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-cli
          path: ./artifacts/macos
        continue-on-error: true

      - name: Create Release Upload List
        run: |
          ls -R ./artifacts
          echo "FILES=$(find ./artifacts -type f -printf '%p ')" >> $GITHUB_ENV

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          files: ${{ env.FILES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
